name: Run Scanner

on:
  schedule:
    - cron: "*/15 4-10 * * 1-5"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install fyers-apiv3 pandas numpy requests

      - run: python nifty_github.py
        env:
          FYERS_CLIENT_ID: ${{ secrets.FYERS_CLIENT_ID }}
          FYERS_ACCESS_TOKEN: ${{ secrets.FYERS_ACCESS_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Commit cache
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add signals.json
          git commit -m "update signals cache" || echo "no changes"
          git push
